### ISSUE TITLE
eb-with-efs-out.yaml stack fails to create.

### ISSUE THREAD

**Issue by ankitsnlq** [guysqr/node-red-ha-on-aws#5]
Hi, 

I'm trying to create cloudformation stack with eb-with-efs-out.yaml file. Used build-cf.py to generate a fresh file. I'm getting error more than one security group matched id: (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 70988de3-1b15-4cf2-945e-fe1815fb59e6). Tried multiple time but it is failing. What can be the reason?

Regards

**Comment by guysqr** [comment]
Are you specifying a sg in the parameters?

Regards

Guy

On 29 Mar 2020, at 3:00 pm, Ankit <notifications@github.com> wrote:

﻿


Hi,

I'm trying to create cloudformation stack with eb-with-efs-out.yaml file. Used build-cf.py to generate a fresh file. I'm getting error more than one security group matched id: (Service: AWSElasticBeanstalk; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 70988de3-1b15-4cf2-945e-fe1815fb59e6). Tried multiple time but it is failing. What can be the reason?

Regards

**Comment by ankitsnlq** [comment]
Hi @guysqr ,

No I'm not specifying any sg. First, when I upload and create stack it gives error Parameter TwilioAuthToken failed to satisfy constraint: Get it from the Twilio console

So I removed TwilioAuthToken part from the stack and provided below parameters and but it fails to create. 

![CloudFormation - Stack](https://user-images.githubusercontent.com/7347629/77886476-8faec080-7286-11ea-9048-b060d8c7dd02.png)

Regards,
Arun Singh

**Comment by guysqr** [comment]
Hi @ankitsnlq, 

Hm. Are you getting a different error now when it fails to create? Or same as the original error? ("more than one security group matched id")

Guy

**Comment by guysqr** [comment]
Hey, I just fixed the twilio issue and ran the stack and it worked without issues. Did you delete the old stack before you tried recreating it?

**Comment by ankitsnlq** [comment]
Hi @guysqr, 

Tested again but the same error. Looks like an issue with vpc stack? As I'm using the same vpc stack. Also, I have used a python script to generate a new eb stack file. 

Regards,

**Comment by guysqr** [comment]
Are you using the VPC stack in this repo, or re-using an existing VPC? The eb template should work with an existing VPC or one created via the CF template in this repo. Perhaps clean up any VPCs you don't need and recreate one using the supplied template and then make sure you are using that VPC and its subnets when you run the eb template?

**Comment by guysqr** [comment]
I've just noticed in your screenshot that additional security group as "-" in it, can you check that that field is instead empty when you run the stack? "-" would not be valid input (have checked the current version and it doesn't default to that value). Perhaps do a git pull and make sure you have the most up-to-date template.

**Comment by guysqr** [comment]
Same with certificate ARN - just leave it blank if you don't have one. 

"-" means something, whereas leaving it blank does not.

**Comment by ankitsnlq** [comment]
Hi @guysqr,

Thank you that helped. Now I have deployed the node red on aws using eb. Thank you so much for continue reply.

**Comment by guysqr** [comment]
No worries!
